name: gather_mvp
description: 메타버스에서 영어회화 하기

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  speech_to_text: ^6.1.1
  avatar_glow: ^2.0.2
  highlight_text: ^1.6.0
  grouped_list: ^5.1.2
  http: ^0.13.5
  google_fonts: ^4.0.3 # 글꼴
  flutter_svg: ^2.0.3 # svg 이미지
  flutter_secure_storage: ^8.0.0 # 로그인 정보 저장
  kakao_flutter_sdk: ^1.4.2 # 카카오 SDK
  provider: ^6.0.5
  url_launcher: ^6.1.10 # 웹 페이지 띄우기
  flutter_login: ^4.1.1 # 간단하게 로그인 만들기
  google_sign_in: ^6.0.2 # 구글 로그인
  flutter_sound: ^9.2.13 # 녹음
  permission_handler: ^10.2.0
  path_provider: ^2.0.14
  mime: ^1.0.4
  http_parser: ^4.0.2
  jumping_dot: ^0.0.4
  auto_size_text_field: ^2.2.1
  auto_size_text: ^3.0.0
  flutter_launcher_icons: ^0.12.0
  table_calendar: ^3.0.9
  intl: ^0.18.0 # locale
  clipboard: ^0.1.3
  sign_in_with_apple: ^4.3.0
  circular_profile_avatar: ^2.0.5
  in_app_purchase: ^3.1.5
  audio_session: ^0.1.13
  introduction_screen: ^3.1.8
  step_progress_indicator: ^1.0.2
  googleapis: ^11.0.0
  googleapis_auth: ^1.4.0
  audioplayers: ^4.0.1
  google_speech: ^2.1.2
  flutter_tts: ^3.6.3
  facebook_app_events: ^0.18.3
  share: ^2.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Thin.otf
          weight: 100
        - asset: assets/fonts/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSansKR-Black.otf
          weight: 900
