// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrPcsyQCr66k_7sbDCn9PDsifohJm5qWg',
    appId: '1:505184773167:web:9d3722b6dd15f1541312da',
    messagingSenderId: '505184773167',
    projectId: 'gather-mvp',
    authDomain: 'gather-mvp.firebaseapp.com',
    storageBucket: 'gather-mvp.appspot.com',
    measurementId: 'G-QCGR6EE6K1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUy2Vxm12Qgw8nI5cO4FQX_lrD20hB5e0',
    appId: '1:505184773167:android:3ff3061822847cfb1312da',
    messagingSenderId: '505184773167',
    projectId: 'gather-mvp',
    storageBucket: 'gather-mvp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSt2bN1hIjW49Ix8V5gQI1bT8C0uliEhY',
    appId: '1:505184773167:ios:ee32e07b0500e6bc1312da',
    messagingSenderId: '505184773167',
    projectId: 'gather-mvp',
    storageBucket: 'gather-mvp.appspot.com',
    iosClientId: '505184773167-mf9m7oi6v9rlia9h67ie495but9lio77.apps.googleusercontent.com',
    iosBundleId: 'com.jungwon.jungmo.gatherMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSt2bN1hIjW49Ix8V5gQI1bT8C0uliEhY',
    appId: '1:505184773167:ios:ee32e07b0500e6bc1312da',
    messagingSenderId: '505184773167',
    projectId: 'gather-mvp',
    storageBucket: 'gather-mvp.appspot.com',
    iosClientId: '505184773167-mf9m7oi6v9rlia9h67ie495but9lio77.apps.googleusercontent.com',
    iosBundleId: 'com.jungwon.jungmo.gatherMvp',
  );
}
